### PR TITLE
[paid 350] $600 Voting Screen Development

### PR DESCRIPTION
**Pull request by aweb3dad**
$500 - development
+20% quality assurance fee = $100 (30 min)
(10% - me, 90% - she)

# Screenshot
image

### CODE REVIEW

**Comment by aweb3dad** [comment]
@milojeBtc beautiful. Always make sure to add screenshots of what features you worked on, still reviewing here

**Comment by aweb3dad** [comment]
@milojeBtc Mind making these changes too, after that you have my approval here
image

**Comment by SHEWAPNG** [comment]
I think we should have a logo image up the logo side 
This is so nice 
We are good to go

**Comment by aweb3dad** [comment]
> I think we should have a logo image up the logo side This is so nice We are good to go

I totally agree. We don't have a logo just yet, so we'll have to go commission a designer to do so.

I'm setting up a meeting with the client on thursday here, so hopefully we can get that into the pipeline here. Have a meeting with my project manager tomorrow who will consult me through all this, so I'll put that on his board as well.

Good idea @SHEWAPNG.

Other than that, were you able to run the app locally? You don't necessarily have to, just asking right now

**Comment by SHEWAPNG** [comment]
I can make logo for the company
I make logos
I'm also a graphic designer
So we might not necessarily have to get someone to do it

**Comment by SHEWAPNG** [comment]
The app is working perfectly
I can be the logo designer
I design graphics too
And logo

**Comment by aweb3dad** [comment]
@SHEWAPNG I hear you, thank you. I'll keep that in mind.

I'll reach out to the client and see if he's ready for logo development there thank you. If you want to draw up a proposal for him, feel free to create a github issue to explain what you want him to approve, and I'll bring that into our meeting here on thursday (planning for thursday to present him all we're doing here)

**Comment by SHEWAPNG** [comment]
Will do, thanks!

**Comment by SHEWAPNG** [comment]
I can create a logo for the app
I design logo
I think you should just create a space for logo up there . Then tell me how
l can come in

**Comment by milojeBtc** [comment]
commit new code.
fix all issues that you pointed out.
plz check it out

**Pull request merged**
